FROM openmetadata/ingestion:1.11.7

USER root
RUN mkdir -p /opt/dbt/nessie_transform && chown -R 50000:0 /opt/dbt

USER airflow

RUN pip install --no-cache-dir \
    "openmetadata-ingestion[iceberg]==1.11.7" \
    "dbt-spark[PyHive]==1.8.0" \
    "pyhive[hive]==0.7.0" \
    requests
